authcart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.handlelogin, name='handlelogin'),
    path('logout/', views.handlelogout, name='handlelogout'),
    path('activate/<uidb64>/<token>/', views.ActivateAccountView.as_view(), name='activate'),
]

cart/urls.py
from django.urls import path
from . import views
 
app_name = 'cart'
 
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ecommerceapp.urls')),
    path('auth/', include('authcart.urls')),
    path('cart/', include('cart.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerceapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
]

authcart/models.py
from django.db import models

# Create your models here.

cart/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
 
    def __str__(self):
        return self.name
 
class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

ecommerceapp/models.py
from django.db import models



# Create your models here.
class Contact(models.Model):
    # contact_id=models.AutoField(primary_key=True)
    name=models.CharField(max_length=50)
    email=models.EmailField()
    desc=models.TextField(max_length=500)
    phonenumber=models.IntegerField()

    def __str__(self):
        return self.name
    
# class Product(models.Model):
#     product_id=models.AutoField
#     product_name=models.CharField(max_length=100)
#     category=models.CharField(max_length=100, default="")
#     subcategory=models.CharField(max_length=50, default="")
#     price=models.IntegerField(default=0)
#     desc=models.CharField(max_length=100)
#     image=models.ImageField(upload_to='images/images')
   

#     def __str__(self):
#         return self.product_name
    

authcart/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View
from django.contrib import messages
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from .utils import TokenGenerator, generate_token
from django.utils.encoding import force_bytes
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.core.mail import EmailMessage
from django.conf import settings


# Create your views here.

def handlelogin(request):
    if request.method=="POST":
        username=request.POST['email']
        userpassword=request.POST['pass1']
        myuser=authenticate(username=username,password=userpassword)

        if myuser is not None:
            login(request,myuser)
            messages.success(request,"Login Success")
            return redirect('/cart')
        
        else:
            messages.error(request,"Invalid Credentials")
            return redirect('/auth/login')
        
    return render(request,'login.html')


def signup(request):
    if request.method=="POST":
        email=request.POST['email']
        password=request.POST['pass1']
        confirm_password=request.POST['pass2']
        if password!=confirm_password:
            messages.warning(request, "password is not matching")
            return render(request, 'signup.html')

        try:
            if User.objects.get(username=email):
                # return HttpResponse("email already exist")
                messages.info(request, "Email is Taken")
                return render(request, 'signup.html')
            
        except Exception as identifier:
            pass
        user = User.objects.create_user(email,email,password)
        user.is_active=False
        user.save()
        email_subject="Activate Your Account"
        message=render_to_string('activate.html',{
            'user':user,
            'domain':'127.0.0.1:8000',
            'uid':urlsafe_base64_encode(force_bytes(user.pk)),
            'token':generate_token.make_token(user)

        })

        email_message = EmailMessage(email_subject,message,settings.EMAIL_HOST_USER,
        [email])
        email_message.send()
        messages.success(request,"Activate Your Account by clicking the link in your gmail")
        return redirect('/auth/login/')
    return render(request, 'signup.html')


class ActivateAccountView(View):
    def get(self,request,uidb64,token):
        try:
            uid=force_text(urlsafe_base64_decode(uidb64))
            user=User.objects.get(pk=uid)
        except Exception as identifier:
            user=None
        if user is not None and generate_token.check_token(user,token):
            user.is_active=True
            user.save()
            messages.info(request,"Account Activated Successfully")
            return redirect('/auth/login')
        return render(request,'activatefail.html')


def handlelogout(request):
    logout(request)
    messages.info(request,"Logout Success")
    return redirect('/auth/login')

cart/views.py
from django.shortcuts import render, redirect
from .models import Product, CartItem


# Create your views here.

def product_list(request):
    products = Product.objects.all()
    return render(request, 'index.html', {'products': products})
 
def view_cart(request):
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, 'cart.html', {'cart_items': cart_items, 'total_price': total_price, "total_cart_item":cart_items.count()})
 
def add_to_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    cart_item, created = CartItem.objects.get_or_create(product=product, user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect('cart:view_cart')
 
def remove_from_cart(request, item_id):
    cart_item = CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('cart:view_cart')
 
 

ecommerceapp/views.py
from django.shortcuts import render
from .models import Contact
from django.contrib import messages
from cart.models import CartItem
# from math import ceil
 
# Create your views here.
def index(request):
    
    if (request.user.is_authenticated):
        total_cart_item = CartItem.objects.filter(user=request.user.id).count()
        return render(request,"index.html",{"total_cart_item": total_cart_item})

    return render(request,"index.html")

def contact(request):
    if request.method=="POST":
        name=request.POST.get("name")
        email=request.POST.get("email")
        desc=request.POST.get("desc")
        pnumber=request.POST.get("pnumber")
        myquery=Contact(name=name,email=email,desc=desc,phonenumber=pnumber)
        myquery.save()
        messages.info(request,"We will get back to you soon..")
    
    if (request.user.is_authenticated):
        total_cart_item = CartItem.objects.filter(user=request.user.id).count()
        return render(request,"contact.html",{"total_cart_item": total_cart_item})

    return render(request, 'contact.html')

def about(request):

    if (request.user.is_authenticated):
        total_cart_item = CartItem.objects.filter(user=request.user.id).count()
        return render(request,"about.html",{"total_cart_item": total_cart_item})
    return render(request, 'about.html')

templates/about.html
{% extends "base.html" %}

{% block title %}
  About Page
{% endblock title %}

{% block body%}
 <h1>About Us</h1>
{% endblock body%}

templates/activate.html
{% autoescape off %}
Hi {{ user.username }},
Please click the link below to verify your account:

http://{{domain}}{% url 'activate' uidb64=uid token=token %}

{% endautoescape %}

templates/activatefail.html
<h1>Something went wrong</h1>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {% block title %} {% endblock title %}
  </title>
  <meta content="ecommerce website we deliver products in 1 hours" name="description">
  <meta content="ecommerce" name="amazon,flipkart,selling,products">


  <!-- Google Fonts -->
  <link
    href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
    rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static '/assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static '/assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static '/assets/css/style.css' %}" rel="stylesheet">

  {% block style %}{% endblock style %}

</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top ">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="/" class="logo"><img src="{% static 'images/logo2.jpg' %}" alt="" class="img-fluid">Shopping Cart</a>


      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="/cart">Home</a></li>
          <li><a class="nav-link scrollto" href="/blog">Blog</a></li>
          <li><a class="nav-link scrollto" href="/about">About</a></li>
          <li><a class="nav-link scrollto" href="/checkout">Checkout</a></li>
          <li><a class="nav-link scrollto" href="/about">My profile</a></li>



          <button type="button" class="nav-link scrollto bg-danger text-white p-3 m-3" id="popcart"
            data-bs-container="body" data-bs-toggle="popover" data-bs-placement="bottom" data-html="true">


            Cart ({% if total_cart_item%}
            {{total_cart_item}}
            {% else %}
            {{0}}
            {% endif %}
            )
          </button>



          {% if request.user.is_authenticated %}
          <li>
            <a class="getstarted scrollto">Welcome {{user.username}}</a>
          </li>

          <li><a class="nav-link scrollto" href="/auth/logout/">Logout


            </a></li>

          {% else %}
          <li class="dropdown"><a href="#"><span>SignIn</span> <i class="bi bi-chevron-down"></i></a>


            <ul>
              <li><a href="/auth/signup/">SignUp</a></li>
              <li><a href="/auth/login/">Login</a></li>
            </ul>
          </li>
          {% endif %}



          {% comment %} <li><a class="nav-link scrollto bg-danger p-3 m-2" href="/contact">Cart</a></li> {% endcomment %}


          <li><a class="nav-link scrollto bg-dark p-3 m-2" href="/contact">Contact</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <!-- ======= Hero Section ======= -->
  <section id="hero">
    <div class="hero-container">

      {% block content %}






      {% endblock content %}

    </div>
  </section><!-- End Hero -->

  <main id="main">

    {% block body %}







    {% endblock body %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>Tempo</h3>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="/">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="/about">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Tempo</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
      class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static '/assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static '/assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static '/assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static '/assets/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static '/assets/js/main.js' %}"></script>


  {% block script %}

  {% endblock script %}

</body>

</html>

templates/cart.html
{% extends "base.html" %}

{% block title %}
    Shopping Cart
{% endblock title %}
{% block content %}

<h1>WELCOME TO GUCCI SALE</h1>


{% endblock content %}
{% block body %} 
{% load static %}

<section id="portfolio" class="portfolio">
    <div class="container">

      {% for message in messages %}

   <div 
      class="alert alert-{{message.tags}} alert-dismissible fade show" 
      role="alert">
     
    <strong>{{message}}</strong>
    <button 
      type="button" 
      class="btn-close" 
      data-bs-dismiss="alert" 
      aria-label="Close"
    ></button>
   </div>
   {% endfor %}

   <h1>Your Shopping Cart</h1>
 
   <div class="">

   

   {% for item in cart_items %}
   <div class="container">
       <p>{{ item.product.name }} ({{ item.quantity }})</p>
       <p>Price: ${{ item.product.price }}</p>
       <a href="{% url 'cart:remove_from_cart' item.id %}">Remove</a>
   </div>
   {% empty %}
   <p>Your cart is empty.</p>
   {% endfor %}

   </div>

   <p>Total Price: ${{ total_price }}</p>

   <a href="{% url 'cart:product_list' %}">Continue Shopping</a>

</body>

</html>

  </section><!-- End Portfolio Section -->



{% endblock body %}

templates/contact.html
{% extends "base.html" %}

{% block title %}
  Contact Page
{% endblock title %}

{% block body%}
 <h1 class="text-center">Contact Us</h1>
 <div class="container mt-2">
  {% for message in messages %}

  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><button>
  </div>
  {% endfor %}

<div class="row">

    <div class="col-md-4"></div>
    <div class="col-md-4">

  <form action="/contact" method="post">
    {% csrf_token %}
    <br>
    <label for="name">Full Name</label>
    <div class="form-group">
      <input 
        type="text" 
        class="form-control p-2" 
        id="name" 
        name="name" 
        required 
      />
    </div>

    <label for="email">Email</label>
    <div class="form-group">
      <input 
        type="email" 
        class="form-control p-2" 
        id="email" 
        name="email" 
        value="{{user.email}}"
        required 
        />
    </div>

    <label for="desc">How Can I Help You?</label>
    <div class="form-group">
      <textarea 
        type="text" 
        class="form-control p-2" 
        id="desc" name="desc" 
        required> </textarea>
    </div>

    <label for="pnumber">Phone Number</label>
    <div class="form-group">
      <input 
        type="number" 
        class="form-control p-2" 
        id="pnumber"
        name="pnumber" 
        required
        />
    </div>

    <br />
    <button type="submit" class="btn btn-dark">Submit</button>
  
    <br />
    
  </form>

    </div>
    <div class="col-md-4"></div>

</div>




 </div>
{% endblock body%}

templates/copy.html
{% for product, range, nSlides in allProds %}

<h3 class="my-3 text-center text-success bg-light"> 
  {{product.0.category}} Flashsale
</h3>

<div class="container">
  <div class="row">
    {% for i in product %}
    <div class="col-md-3 mt-3">
      <img src='/media/{{i.image}}' class="card-img-top" alt="not found" 
      height="200px" width="150px" />
        <div class="card-body">
          <h5 class="card-title" id="namepr{{i.id}}">{{i.product_name}}</h5>
          <p class="card-text">{{i.desc|slice:"0:53"}} ... </p>
            <h6 class="card-title mb-3">
              Price:<span id="pricepr{{i.id}}">{{i.price}}</span>
            </h6>
            <span id="divpr{{i.id}}" class="divpr">
              <button id="pr{{i.id}}" class="btn btn-danger btn-sm mt-0">
                AddToCart
              </button>
            </span>

          <a href="/media/{{i.image}}"> 
          <button class="btn btn-dark btn-sm cart">View</button>
          </a>

        </div>
        </div>

        {% endfor %}

        </div> 
     </div>

     {% endfor %}
    </div>



    

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
   
 
   <script>
 
     //find pout the card from local storage
 
     if (localStorage.getItem('cart') == null) {
         var cart = {};
     } else {
         cart = JSON.parse(localStorage.getItem('cart'));
         updateCart(cart);
 
     }
     // add or increment code
 
     // $(',cart').click(function() {
       $('.divpr').on('click', 'button.cart', function() {
 
         var idstr = this.id.toString();
       
 
         if (cart[idstr] != undefined) {
             qty = cart[idstr][0] + 1;
 
         } else {
             qty = 1;
             name = document.getElementById('namepr' + i.id).innerHTML;
             price = document.getElementById('pricepr' + i.id).innerHTML;
             cart[idstr] = [qty, name, price];
 
         }
         updateCart(cart);
 
         localStorage.setItem('cart', JSON.stringify(cart));
         document.getElementById('cart').innerHTML = Object.keys(cart).length;
     });
     
     // add popover to cart
 
 $('#popcart').popover();
 
 updatePopover(cart); 
 
 function updatePopover(cart) {
     console.log('we are inside update popover');
     var popStr = "";
 
     var popStr = popStr = `<h5>Cart for your items in my shopping cart</h5><div class='mx-2 my-2'>`;
  
     <div class='mx-2 my-2'>";
     var i = 1;
     for (var item in cart) {
         popStr = popStr + "<b>" + i + "</b>. ";
         popStr = popStr + document.getElementById('name' + item).innerHTML
             .slice(0, 19) + "..." + "<b>" +cart[item][0] + "</b>"+ "Qty" + '<br>';
 
         i = i + 1;
     } 
     
     popStr = popStr + "</div> <a href='/checkout'><button class='btn btn-success' id='clearCart'>Checkout</button></a> <button class='btn btn-dark' onclick='clearCart()' id='clearCart'>ClearCart</button>";
 
     document.getElementById('popcart').setAttribute('data-content', popStr);
     $('#popcart').popover('show');
 
 }
     
 function clearCart() {
     cart = JSON.parse(localStorage.getItem('cart'));
     for (var item in cart) {
         document.getElementById('div' + item).innerHTML = '<button id"' + 
         item + '" class="btn btn-success cart">Add to Card</button>'
     }
     localStorage.clear();
     cart = {};
     updateCart(cart);
 }
 
 function updateCart(cart) {
     var sum = 0;
     for (var item in cart) {
         sum = sum + cart[item][0];
         document.getElementById('div' + item).innerHTML = "<button id='minus" 
         + item + "' class='btn btn-success minus'>-</button> <span id='val" + 
         item + "''>" + cart[item][0] + "</span> <button id='plus" + item + "' 
         class='btn btn-success plus'> + </button>";
     }
     localStorage.setItem('cart', JSON.stringify(cart));
     document.getElementById('cart').innerHTML = sum;
     console.log(cart);
     updatePopover(cart);
 }
 
     //if plus or minus button is clicked change the cart as well as the display value
     $('.divpr').on("click", "button.minus", function() {
 
       a = this.id.slice(7, );
       cart['pr' + a][0] = cart['pr' + a][0] - 1;
       cart['pr' + a][0] = Math.max(0, cart['pr' + a][0]);
       document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
       updateCart(cart);
       
     })
 
 
     $('.divpr').on("click", "button.plus", function() {
 
       a = this.id.slice(6, );
       cart['pr' + a][0] = cart['pr' + a][0] + 1;
 
       document.getElementById('valpr' + a).innerHTML = cart['pr' + a][0];
       updateCart(cart);
 
 
       
     })
   </script>

   allProds = []
    catprods = Product.objects.values('category','id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod= Product.objects.filter(category=cat)
        n=len(prod)
        nSlides = n // 4 + ceil((n / 4) - (n // 4))
        allProds.append([prod, range(1, nSlides), nSlides])

    params= {'allProds':allProds}


    <div class="row">
      <div class="col-sm-6 mb-3 mb-sm-0">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Special title treatment</h5>
            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
    </div>

templates/index.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock title %}
{% block content %}

<h1>WELCOME TO GUCCI SALE</h1>


{% endblock content %}
{% block body %} 
{% load static %}

<section id="portfolio" class="portfolio">
    <div class="container">

      {% for message in messages %}

   <div 
      class="alert alert-{{message.tags}} alert-dismissible fade show" 
      role="alert">
     
    <strong>{{message}}</strong>
    <button 
      type="button" 
      class="btn-close" 
      data-bs-dismiss="alert" 
      aria-label="Close"
    ></button>
   </div>
   {% endfor %}

      <div class="section-title">
        <h2>Welcome to Shop</h2>
        <h3>Check our <span>Products</span></h3>
      </div>
       <div class="container justify-content-center">
        <div class="row">
        {% for product in products %}
            <div class="col-md-3 mt-3">
                <div class="card-body">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" width="150px" height="200px">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <h6 class="card-title mb-3">Price: ${{ product.price }}</h6>
                <a href="#" class="btn btn-dark w-100 py-2">Buy Now</a>
                <a class="btn btn-danger w-100 py-2" href="{% url 'cart:add_to_cart' product.id %}">Add to Cart</a>
                </div>
            </div>
        {% endfor %}
          </div>
        </div>
  </section><!-- End Portfolio Section -->



{% endblock body %}

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock title %}
{% block content %}





<div class="card bg-light p-5">
  
  {% for message in messages %}

  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><button>
  </div>
  {% endfor %}

<h3 data-aos="fade-up" class="text-dark">Login</h3>

  <form method="POST">
    {% csrf_token %}
    <br>
  
    <label for="email">Email</label>
    <div class="form-group">
      <input type="email" class="form-control p-2" id="email" name="email" required />
    </div>
    <label for="pass1">Password</label>
    <div class="form-group">
      <input type="password" class="form-control p-2" id="pass1" name="pass1" required />
    </div>
    <br>
    <button type="submit" class="btn btn-dark">Login</button>
  
    <br>
    New User? <a href="/auth/signup/">Signp</a>
    
  </form>

</div>

{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% block title %}Signup{% endblock title %}
{% block content %}





<div class="card bg-light p-5">
  
  {% for message in messages %}

  <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"><button>
  </div>
  {% endfor %}

<h3 data-aos="fade-up" class="text-dark">Signup</h3>

  <form action="/auth/signup/" method="post">
    {% csrf_token %}
    <br>
  
    <label for="email">Email</label>
    <div class="form-group">
      <input type="email" class="form-control p-2" id="email" name="email" required >
    </div>
    <label for="pass1">Password</label>
    <div class="form-group">
      <input type="password" class="form-control p-2" id="pass1" name="pass1" required>
    </div>
    <label for="pass2">Confirm Password</label>
    <div class="form-group">
      <input type="password" class="form-control p-2" id="pass2" name="pass2" required>
    </div>
    <br>
    <button type="submit" class="btn btn-dark">SignIn</button>
  
    <br>
    Already User? <a href="/auth/login/">Login</a>
    
  </form>

</div>

{% endblock content %}